MediconEFC/Models/PrecoPlano.cs
using MediconEFC.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MediconEFC.Models
{
    public class PrecoPlano
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public FaixaEtaria FaixaEtaria { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int FaixaEtariaId { get; set; }
        public TipoAcomodacao TipoAcomodacao { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int TipoAcomodacaoId { get; set; }
        public AbrangenciaPlano AbrangenciaPlano { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int AbrangenciaPlanoId { get; set; }
        public TipoContrato TipoContrato { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int TipoContratoId { get; set; }
        public TipoPlano TipoPlano { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int TipoPlanoId { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public double Valor { get; set; }
        public string Observacao { get; set; }
        public bool Ativo { get; set; }

        public PrecoPlano()
        {

        }

        public PrecoPlano(int id, FaixaEtaria faixaEtaria, int faixaEtariaId, TipoAcomodacao tipoAcomodacao, int tipoAcomodacaoId, AbrangenciaPlano abrangenciaPlano ,int abrangenciaPlanoId, TipoContrato tipoContrato, TipoPlano tipoPlano, int tipoContratoId, int tipoPlanoId, double valor, string observacao, bool ativo)
        {
            Id = id;
            FaixaEtaria = faixaEtaria;
            FaixaEtariaId = faixaEtariaId;
            TipoAcomodacao = tipoAcomodacao;
            TipoAcomodacaoId = tipoAcomodacaoId;
            AbrangenciaPlano = abrangenciaPlano;
            AbrangenciaPlanoId = abrangenciaPlanoId;
            TipoContrato = tipoContrato;
            TipoContratoId = tipoContratoId;
            TipoPlano = tipoPlano;
            TipoPlanoId = tipoPlanoId;
            Valor = valor;
            Observacao = observacao;
            Ativo = ativo;
        }
    }
}

MediconEFC/Models/ViewModels/PrecoPlanoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediconEFC.Models
{
    public class PrecoPlanoViewModel
    {
        public PrecoPlano precoPlano { get; set; }
        public FaixaEtaria faixaEtaria { get; set; }
        public TipoAcomodacao tipoAcomodacao { get; set; }
        public AbrangenciaPlano abrangenciaPlano { get; set; }
        public TipoContrato tipoContrato { get; set; }
        public TipoPlano tipoPlano { get; set; }

        public ICollection<PrecoPlano> listaPrecoPlano { get; set; }
        public ICollection<FaixaEtaria> listaFaixaEtaria { get; set; }
        public ICollection<TipoAcomodacao> listaTipoAcomodacao { get; set; }
        public ICollection<AbrangenciaPlano> listaAbrangenciaPlano { get; set; }
        public ICollection<TipoContrato> listaTipoContrato { get; set; }
        public ICollection<TipoPlano> listaTipoPlano { get; set; }
    }
}

MediconEFC/Controllers/PrecoPlanoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MediconEFC.Data;
using MediconEFC.Models;
using MediconEFC.Services;
using System.Diagnostics;

namespace MediconEFC.Controllers
{
    public class PrecoPlanoController : Controller
    {
        private readonly MediconEFCContext _context;
        private readonly PrecoPlanoService _precoPlanoService;
        private readonly MensagemService _mensagemService;


        public PrecoPlanoController(MediconEFCContext context, PrecoPlanoService precoPlanoService, MensagemService mensagemService)
        {
            _context = context;
            _precoPlanoService = precoPlanoService;
            _mensagemService = mensagemService;
        }

        // GET: PrecoPlano
        public async Task<IActionResult> Index()
        {
            var listaPrecoPlano = await _precoPlanoService.FindAllAsync();
            IEnumerable<PrecoPlanoViewModel> model = ConverterPrecoPlanoParaPrecoPlanoViewModel(listaPrecoPlano);
            return View(model);
        }

        // GET: PrecoPlano/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            //FindByIdAsync
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Preço Plano não encontrado!" });
            }

            var obj = await _precoPlanoService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Preço Plano não encontrado!" });
            }

            return View(obj);
        }

        // GET: PrecoPlano/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["AbrangenciaPlanoId"] = new SelectList(_context.AbrangenciaPlano, "Id", "Nome");
            //ViewData["FaixaEtariaId"] = new SelectList(_context.FaixaEtaria, "Id", "Descricao");
            //ViewData["TipoAcomodacaoId"] = new SelectList(_context.TipoAcomodacao, "Id", "Nome");
            //ViewData["TipoContratoId"] = new SelectList(_context.TipoContrato, "Id", "Nome");
            //ViewData["TipoPlanoId"] = new SelectList(_context.TipoPlano, "Id", "Nome");


            var _listaAbrangenciaPlano = await _context.AbrangenciaPlano.ToListAsync();
            var _listaFaixaEtaria = await _context.FaixaEtaria.ToListAsync();
            var _listaTipoAcomodacao = await _context.TipoAcomodacao.ToListAsync();
            var _listaTipoContrato = await _context.TipoContrato.ToListAsync();
            var _listaTipoPlano = await _context.TipoPlano.ToListAsync();
            var viewModel = new PrecoPlanoViewModel
            {
                listaAbrangenciaPlano = _listaAbrangenciaPlano,
                listaFaixaEtaria = _listaFaixaEtaria,
                listaTipoAcomodacao = _listaTipoAcomodacao,
                listaTipoContrato = _listaTipoContrato,
                listaTipoPlano = _listaTipoPlano
            };


            return View(viewModel);
        }

        // POST: PrecoPlano/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FaixaEtariaId,TipoAcomodacaoId,AbrangenciaPlanoId,TipoContratoId,TipoPlanoId,Valor,Observacao,Ativo")] PrecoPlano precoPlano)
        {
            if (ModelState.IsValid)
            {
                _context.Add(precoPlano);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AbrangenciaPlanoId"] = new SelectList(_context.AbrangenciaPlano, "Id", "Nome", precoPlano.AbrangenciaPlanoId);
            ViewData["FaixaEtariaId"] = new SelectList(_context.FaixaEtaria, "Id", "Descricao", precoPlano.FaixaEtariaId);
            ViewData["TipoAcomodacaoId"] = new SelectList(_context.TipoAcomodacao, "Id", "Nome", precoPlano.TipoAcomodacaoId);
            ViewData["TipoContratoId"] = new SelectList(_context.TipoContrato, "Id", "Nome", precoPlano.TipoContratoId);
            ViewData["TipoPlanoId"] = new SelectList(_context.TipoPlano, "Id", "Nome", precoPlano.TipoPlanoId);
            return View(precoPlano);
        }

        // GET: PrecoPlano/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var precoPlano = await _context.PrecoPlano.FindAsync(id);
            if (precoPlano == null)
            {
                return NotFound();
            }
            ViewData["AbrangenciaPlanoId"] = new SelectList(_context.AbrangenciaPlano, "Id", "Nome", precoPlano.AbrangenciaPlanoId);
            ViewData["FaixaEtariaId"] = new SelectList(_context.FaixaEtaria, "Id", "Descricao", precoPlano.FaixaEtariaId);
            ViewData["TipoAcomodacaoId"] = new SelectList(_context.TipoAcomodacao, "Id", "Nome", precoPlano.TipoAcomodacaoId);
            ViewData["TipoContratoId"] = new SelectList(_context.TipoContrato, "Id", "Nome", precoPlano.TipoContratoId);
            ViewData["TipoPlanoId"] = new SelectList(_context.TipoPlano, "Id", "Nome", precoPlano.TipoPlanoId);
            return View(precoPlano);
        }

        // POST: PrecoPlano/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FaixaEtariaId,TipoAcomodacaoId,AbrangenciaPlanoId,TipoContratoId,TipoPlanoId,Valor,Observacao,Ativo")] PrecoPlano precoPlano)
        {
            if (id != precoPlano.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(precoPlano);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrecoPlanoExists(precoPlano.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AbrangenciaPlanoId"] = new SelectList(_context.AbrangenciaPlano, "Id", "Nome", precoPlano.AbrangenciaPlanoId);
            ViewData["FaixaEtariaId"] = new SelectList(_context.FaixaEtaria, "Id", "Descricao", precoPlano.FaixaEtariaId);
            ViewData["TipoAcomodacaoId"] = new SelectList(_context.TipoAcomodacao, "Id", "Nome", precoPlano.TipoAcomodacaoId);
            ViewData["TipoContratoId"] = new SelectList(_context.TipoContrato, "Id", "Nome", precoPlano.TipoContratoId);
            ViewData["TipoPlanoId"] = new SelectList(_context.TipoPlano, "Id", "Nome", precoPlano.TipoPlanoId);
            return View(precoPlano);
        }

        // GET: PrecoPlano/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var precoPlano = await _context.PrecoPlano
                .Include(p => p.AbrangenciaPlano)
                .Include(p => p.FaixaEtaria)
                .Include(p => p.TipoAcomodacao)
                .Include(p => p.TipoContrato)
                .Include(p => p.TipoPlano)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (precoPlano == null)
            {
                return NotFound();
            }

            return View(precoPlano);
        }

        // POST: PrecoPlano/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var precoPlano = await _context.PrecoPlano.FindAsync(id);
            _context.PrecoPlano.Remove(precoPlano);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrecoPlanoExists(int id)
        {
            return _context.PrecoPlano.Any(e => e.Id == id);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }


        #region Conversores

        private IEnumerable<PrecoPlanoViewModel> ConverterPrecoPlanoParaPrecoPlanoViewModel(List<PrecoPlano> listaEntrada)
        {
            return listaEntrada != null
                ? listaEntrada.Select(entrada => new PrecoPlanoViewModel()
                {
                    precoPlano = new PrecoPlano()
                    {
                        Id = entrada.Id,
                        Valor = entrada.Valor,
                        Observacao = entrada.Observacao,
                        Ativo = entrada.Ativo,
                        FaixaEtariaId = entrada.FaixaEtariaId,
                        TipoAcomodacaoId = entrada.TipoAcomodacaoId,
                        AbrangenciaPlanoId = entrada.AbrangenciaPlanoId,
                        TipoContratoId = entrada.TipoContratoId,
                        TipoPlanoId = entrada.TipoPlanoId
                    },
                    faixaEtaria = new FaixaEtaria()
                    {
                        Id = entrada.FaixaEtaria.Id,

MediconEFC/Views/PrecoPlano/Create.cshtml
@model MediconEFC.Models.PrecoPlanoViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Cadastrar preço plano</h3>
        </div>
    </div>
    <hr />


    <div class="row-fluid">
        <div class="block">

            <div class="form-group">
                <form asp-action="Create" id="myformCreate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.FaixaEtaria" class="control-label"></label>

                        <select asp-for="precoPlano.FaixaEtaria" id="cboFaixaEtaria" asp-items="@(new SelectList(Model.listaFaixaEtaria,"Id", "Descricao"))" class="form-control chosen-select"><option>Selecione</option></select>
                        <input type="hidden" asp-route-id="" asp-for="precoPlano.FaixaEtariaId" id="idFaixaEtariaSelecionada" />
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.TipoAcomodacao" class="control-label"></label>

                        <select asp-for="precoPlano.TipoAcomodacao" id="cboTipoAcomodacao" asp-items="@(new SelectList(Model.listaTipoAcomodacao,"Id", "Nome"))" class="form-control chosen-select"><option>Selecione</option></select>
                        <input type="hidden" asp-route-id="" asp-for="precoPlano.TipoAcomodacao" id="idTipoAcomodacaoSelecionado" />
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.AbrangenciaPlano" class="control-label"></label>

                        <select asp-for="precoPlano.AbrangenciaPlano" id="cboAbrangenciaPlano" asp-items="@(new SelectList(Model.listaAbrangenciaPlano,"Id", "Nome"))" class="form-control chosen-select"><option>Selecione</option></select>
                        <input type="hidden" asp-route-id="" asp-for="precoPlano.AbrangenciaPlano" id="idAbrangenciaPlanoSelecionado" />
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.TipoContrato" class="control-label"></label>

                        <select asp-for="precoPlano.TipoContrato" id="cboTipoContrato" asp-items="@(new SelectList(Model.listaTipoContrato,"Id", "Nome"))" class="form-control chosen-select"><option>Selecione</option></select>
                        <input type="hidden" asp-route-id="" asp-for="precoPlano.TipoContrato" id="idTipoContratoSelecionado" />
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.TipoPlano" class="control-label"></label>

                        <select asp-for="precoPlano.TipoPlano" id="cboTipoPlano" asp-items="@(new SelectList(Model.listaTipoPlano,"Id", "Nome"))" class="form-control chosen-select"><option>Selecione</option></select>
                        <input type="hidden" asp-route-id="" asp-for="precoPlano.TipoPlano" id="idTipoPlanoSelecionado" />
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.Valor" class="control-label"></label>
                        <input asp-for="precoPlano.Valor" class="form-control" />
                        <span asp-validation-for="precoPlano.Valor" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="precoPlano.Observacao" class="control-label"></label>
                        <input asp-for="precoPlano.Observacao" class="form-control" />
                        <span asp-validation-for="precoPlano.Observacao" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-offset-9">
                        <input type="submit" value="Create" class="btn btn-success cssDeleteConfirm" />
                        <a asp-action="Index" class="btn btn-info">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalValidacao" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemValidacao"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgValidacao"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalValidacao" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {
            ////--------------------------Cbo--------------------------
            $('.chosen-select').chosen();
            $('.chosen-select-deselect').chosen({ allow_single_deselect: true });

            $('#myformCreate').on('submit', function (e) {
                e.preventDefault();
                //Seta o id do corretor selecionado
                $('#idFaixaEtariaSelecionada').val($("#cboFaixaEtaria").val());
                $('#idTipoAcomodacaoSelecionado').val($("#cboTipoAcomodacao").val());
                $('#idAbrangenciaPlanoSelecionado').val($("#cboAbrangenciaPlano").val());
                $('#idTipoContratoSelecionado').val($("#cboTipoContrato").val());
                $('#idTipoPlanoSelecionado').val($("#cboTipoPlano").val());

                if ($("#cboFaixaEtaria").val() == 'Selecione') {
                    $("#tipoMensagemValidacao").text("Mensgem de alerta");
                    $("#MsgValidacao").html("Por favor escolha uma Faixa Etária para finalizar cadastro!");
                    $('#ModalValidacao').modal("show");
                } else if ($("#cboTipoAcomodacao").val() == 'Selecione') {
                    $("#tipoMensagemValidacao").text("Mensgem de alerta");
                    $("#MsgValidacao").html("Por favor escolha um Tipo acomodação para finalizar cadastro!");
                    $('#ModalValidacao').modal("show");
                } else if ($("#cboAbrangenciaPlano").val() == 'Selecione') {
                    $("#tipoMensagemValidacao").text("Mensgem de alerta");
                    $("#MsgValidacao").html("Por favor escolha Abrangência Plano para finalizar cadastro!");
                    $('#ModalValidacao').modal("show");
                } else if ($("#cboTipoContrato").val() == 'Selecione') {
                    $("#tipoMensagemValidacao").text("Mensgem de alerta");
                    $("#MsgValidacao").html("Por favor escolha Tipo Contrato para finalizar cadastro!");
                    $('#ModalValidacao').modal("show");
                } else if ($("#cboTipoPlano").val() == 'Selecione') {
                    $("#tipoMensagemValidacao").text("Mensgem de alerta");
                    $("#MsgValidacao").html("Por favor escolha Tipo Plano para finalizar cadastro!");
                    $('#ModalValidacao').modal("show");
                }
                else {
                    //Enviar o formulário inteiro para controller "model"
                    var formData = $(this).serialize();
                    if (!formData.match(/=&|=$/)) {

                        $.post('/PrecoPlano/CadastrarPrecoPlano', formData, function (data) {
                            $("#tipoMensagemResult").text(data.TituloMensagem);
                            $("#MsgResult").html(data.DescricaoMensagem);
                            $('#ModalResult').modal("show");

                        });
                    }
                }
            });

             $("#btnFecharModalResult").click(function () {
                window.location.href = '@Url.Action("Index", "PrecoPlano")';
            });


            $('#btnFecharModalValidacao').on('click', function () {
                $("#ModalValidacao").modal("hide");
            });

        });
    </script>
}

MediconEFC/Views/PrecoPlano/Delete.cshtml
@model MediconEFC.Models.PrecoPlano

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PrecoPlano</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FaixaEtaria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FaixaEtaria.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoAcomodacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoAcomodacao.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AbrangenciaPlano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbrangenciaPlano.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoContrato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoContrato.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoPlano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoPlano.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MediconEFC/Views/PrecoPlano/Details.cshtml
@model MediconEFC.Models.PrecoPlano

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PrecoPlano</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FaixaEtaria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FaixaEtaria.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoAcomodacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoAcomodacao.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AbrangenciaPlano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbrangenciaPlano.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoContrato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoContrato.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoPlano)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoPlano.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MediconEFC/Views/PrecoPlano/Edit.cshtml
@model MediconEFC.Models.PrecoPlano

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>PrecoPlano</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FaixaEtariaId" class="control-label"></label>
                <select asp-for="FaixaEtariaId" class="form-control" asp-items="ViewBag.FaixaEtariaId"></select>
                <span asp-validation-for="FaixaEtariaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoAcomodacaoId" class="control-label"></label>
                <select asp-for="TipoAcomodacaoId" class="form-control" asp-items="ViewBag.TipoAcomodacaoId"></select>
                <span asp-validation-for="TipoAcomodacaoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbrangenciaPlanoId" class="control-label"></label>
                <select asp-for="AbrangenciaPlanoId" class="form-control" asp-items="ViewBag.AbrangenciaPlanoId"></select>
                <span asp-validation-for="AbrangenciaPlanoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoContratoId" class="control-label"></label>
                <select asp-for="TipoContratoId" class="form-control" asp-items="ViewBag.TipoContratoId"></select>
                <span asp-validation-for="TipoContratoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoPlanoId" class="control-label"></label>
                <select asp-for="TipoPlanoId" class="form-control" asp-items="ViewBag.TipoPlanoId"></select>
                <span asp-validation-for="TipoPlanoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observacao" class="control-label"></label>
                <input asp-for="Observacao" class="form-control" />
                <span asp-validation-for="Observacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>