MediconEFC/Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MediconEFC.Data;
using MediconEFC.Models;
using MediconEFC.Services;
using Newtonsoft.Json;
using Medicon.UtilLocal;
using System.Diagnostics;

namespace MediconEFC.Controllers
{
    public class EquipeController : Controller
    {
        private readonly MediconEFCContext _context;
        private readonly EquipeService _equipeService;
        private readonly MensagemService _mensagemService;
        private readonly CorretorService _corretorService;

        public EquipeController(MediconEFCContext context, EquipeService equipeService, MensagemService mensagemService, CorretorService corretorService)
        {
            _context = context;
            _equipeService = equipeService;
            _mensagemService = mensagemService;
            _corretorService = corretorService;
        }

        // GET: Equipe
        public async Task<IActionResult> Index()
        {
            var listaEquipe = await _equipeService.FindAllAsync();
            IEnumerable<EquipeViewModel> model = ConverterEquipeParaEquipeViewModel(listaEquipe);
            return View(model);
        }

        // GET: Equipe/Create
        public async Task<IActionResult> Create()
        {
            var listaCorretor = await _corretorService.FindAllAsync();
            var viewModel = new EquipeViewModel { listaCorretor = listaCorretor };
            //viewModel.Equipe = new Equipe();

            return View(viewModel);
        }

        // GET: Equipe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Equipe não encontrada!" });
            }

            var equipe = await _equipeService.FindByIdAsync(id.Value);
            if (equipe == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id not found" });
            }

            List<Corretor> lstCorretor = await _corretorService.FindAllAsync();
            EquipeViewModel viewModel = new EquipeViewModel { Equipe = equipe, listaCorretor = lstCorretor };
            return View(viewModel);
        }
        
        // GET: Equipe/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Equipe não encontrado!" });
            }

            var model = await _equipeService.FindByIdAsync(id.Value);

            if (model == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Equipe não encontrado!" });
            }

            return View(model);
        }

        private bool EquipeExists(int id)
        {
            return _context.Equipe.Any(e => e.Id == id);
        }

        #region chamadas ajax


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CadastrarEquipe(EquipeViewModel modelEquipe, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();
            if (ModelState.IsValid)
            {
                if (!_equipeService.ExistsEquipe(modelEquipe.Equipe))
                {
                    try
                    {
                        modelEquipe.Equipe.Ativo = true;//TODO: Sempre que for cadastro já setar como ativo e tirar a opção da tela para que o usuário não cadastre uma equipe inativa.
                        _equipeService.CadastrarEquipe(modelEquipe.Equipe);

                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_110).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_110).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemSucesso;
                    }
                    catch (Exception)
                    {
                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_118).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_118).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemErro;

                    }
                }
                else
                {
                    data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_119).Numero;
                    data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_119).Decricao;
                    data.RedirecionarHome = true;
                    data.TituloMensagem = Constantes.TituloMensagemAlerta;
                }

                return Json(data, serializerSettings);
            }
            else
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_118).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_118).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

                return Json(data, serializerSettings);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AlterarEquipe(EquipeViewModel modelEquipe, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            if (modelEquipe.Equipe.Id <= 0 || !ModelState.IsValid)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_115).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_115).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            try
            {
                _equipeService.AlterarEquipe(ConverterEquipeViewModelParaEquipe(modelEquipe));

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_117).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_117).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (ApplicationException)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_112).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_112).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

            }

            return Json(data, serializerSettings);
        }

        public JsonResult ExcluirEquipe(int id, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            try
            {
                _equipeService.RemoveEquipe(id);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_114).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_114).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (Exception)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_113).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_113).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            return Json(data, serializerSettings);
        }

        #endregion

        #region conversores

        private IEnumerable<EquipeViewModel> ConverterEquipeParaEquipeViewModel(List<Equipe> listaEntrada)
        {
            return listaEntrada != null
                ? listaEntrada.Select(entrada => new EquipeViewModel()
                {
                    Equipe = new Equipe()
                    {
                        Id = entrada.Id,
                        Nome = entrada.Nome,
                        Telefone = entrada.Telefone,
                        Contato = entrada.Contato,
                        Ativo = entrada.Ativo,
                        CorretorId = entrada.CorretorId,
                    },
                    Corretor = new Corretor()
                    {
                        Id = entrada.Corretor.Id,
                        Nome = entrada.Corretor.Nome,
                        Ativo = entrada.Corretor.Ativo
                    }

                }).ToList()
            :
            null;
        }

        private Equipe ConverterEquipeViewModelParaEquipe(EquipeViewModel entrada)
        {
            Equipe saida = null;
            if (entrada != null)
            {
                saida = new Equipe();
                saida = entrada.Equipe;
            }

            return saida;
        }

        #endregion

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

MediconEFC/Controllers/PlanoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MediconEFC.Data;
using MediconEFC.Models;
using MediconEFC.Services;
using Medicon.UtilLocal;
using Newtonsoft.Json;

namespace MediconEFC.Controllers
{
    public class PlanoController : Controller
    {
        private readonly MediconEFCContext _context;
        private readonly PlanoService _planoService;
        private readonly MensagemService _mensagemService;

        public PlanoController(MediconEFCContext context, PlanoService planoService, MensagemService mensagemService)
        {
            _context = context;
            _planoService = planoService;
            _mensagemService = mensagemService;
        }

        #region chamadas assincronas

        // GET: Plano
        public async Task<IActionResult> Index()
        {
            var model = await _planoService.FindAllAsync();
            return View(model);
        }

        // GET: Plano/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: Plano/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Plano não encontrado!" });
            }

            var obj = await _planoService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Plano não encontrado!" });
            }

            return View(obj);
        }

        // GET: Plano/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Plano não encontrado!" });
            }

            var obj = await _planoService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Plano não encontrado!" });
            }

            return View(obj);
        }

        #endregion

        #region chamadas ajax

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CadastrarPlano(Plano plano, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();
            if (ModelState.IsValid)
            {
                if (!_planoService.ExistsPlano(plano))
                {
                    try
                    {
                        _planoService.CadastrarPlano(plano);

                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_107).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_107).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemSucesso;
                    }
                    catch (Exception)
                    {
                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemErro;

                    }
                }
                else
                {
                    data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_109).Numero;
                    data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_109).Decricao;
                    data.RedirecionarHome = true;
                    data.TituloMensagem = Constantes.TituloMensagemAlerta;
                }

                return Json(data, serializerSettings);
            }
            else
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

                return Json(data, serializerSettings);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AlterarPlano(int id, Plano plano, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            if (id != plano.Id || !ModelState.IsValid)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_104).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_104).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            try
            {
                 _planoService.AlterarPlano(plano);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_100).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_100).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (ApplicationException)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

            }

            return Json(data, serializerSettings);
        }

        public JsonResult ExcluirPlano(int id, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            try
            {
                _planoService.RemovePlano(id);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_103).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_103).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (Exception)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_108).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            return Json(data, serializerSettings);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }

        #endregion
    }
}

MediconEFC/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediconEFC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-spacelab.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MediconEFC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MediconEFC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MediconEFC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Medicon</title>

    <environment include="Development">
        @*


        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Cerulean.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cyborg.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-journal.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-paper.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-simplex.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-slate.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-yeti.css" />
            ------------------------------Testados ------------------------------------------------
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-sandstone.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-superhero.css" />

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-spacelab.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
        *@

        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />*@




        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/bootstrap-chosen.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/datatables/DT_bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sistema Medicon</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @*<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Cadastro <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li> <a asp-area="" asp-controller="Plano" asp-action="Index" class="dropdown-toggle">Plano</a></li>
                                <li> <a asp-area="" asp-controller="Equipe" asp-action="Index" class="dropdown-toggle">Equipe</a></li>
                                <li> <a asp-area="" asp-controller="Corretor" asp-action="Index" class="dropdown-toggle">Corretor</a></li>
                                <li> <a asp-area="" asp-controller="Cliente" asp-action="Index" class="dropdown-toggle">Cliente</a></li>
                                <li> <a asp-area="" asp-controller="PrecoPlano" asp-action="Index" class="dropdown-toggle">Preço plano</a></li>
                                <li> <a asp-area="" asp-controller="Proposta" asp-action="Index" class="dropdown-toggle">Proposta</a></li>
                                <li> <a asp-area="" asp-controller="Dependente" asp-action="Index" class="dropdown-toggle">Dependente</a></li>
                                <li> <a asp-area="" asp-controller="FaixaEtaria" asp-action="Index" class="dropdown-toggle">Faixa etaria</a></li>

                            </ul>
                        </li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li> <a asp-area="" asp-controller="Plano" asp-action="Index" class="dropdown-toggle">Plano</a></li>
                    <li> <a asp-area="" asp-controller="Equipe" asp-action="Index" class="dropdown-toggle">Equipe</a></li>
                    <li> <a asp-area="" asp-controller="Corretor" asp-action="Index" class="dropdown-toggle">Corretor</a></li>
                    <li> <a asp-area="" asp-controller="Cliente" asp-action="Index" class="dropdown-toggle">Cliente</a></li>
                    <li> <a asp-area="" asp-controller="PrecoPlano" asp-action="Index" class="dropdown-toggle">Preço plano</a></li>
                    <li> <a asp-area="" asp-controller="Proposta" asp-action="Index" class="dropdown-toggle">Proposta</a></li>
                    <li> <a asp-area="" asp-controller="Dependente" asp-action="Index" class="dropdown-toggle">Dependente</a></li>
                    <li> <a asp-area="" asp-controller="FaixaEtaria" asp-action="Index" class="dropdown-toggle">Faixa etaria</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <br />
        @RenderBody()

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0

            </div>
            <strong>Copyright &copy; @DateTime.Now.Year - <a href="https://www.asp.net/">V3MSoluções Obs. Informações meramente ilustrativas não tem nenhum valor para comercialização! </a></strong>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/chosen.jquery.js" asp-append-version="true"></script>


        <script src="~/js/jquery.inputmask/jquery.inputmask.js" asp-append-version="true"></script>
        <script src="~/js/jquery.inputmask/jquery.inputmask.date.extensions.js" asp-append-version="true"></script>
        <script src="~/js/jquery.inputmask/jquery.inputmask.extensions.js" asp-append-version="true"></script>
        <script src="~/js/jquery.inputmask/jquery.inputmask.numeric.extensions.js" asp-append-version="true"></script>
        <script src="~/js/jquery.inputmask/jquery.inputmask.phone.extensions.js" asp-append-version="true"></script>
        <script src="~/js/jquery.inputmask/jquery.inputmask.regex.extensions.js" asp-append-version="true"></script>


        @* ----------------# scripts adiconado por usuário # -------------------- *@
        <script src="~/lib/bootstrap/dist/js/datatables/jquery.dataTables.js"></script>
        <script src="~/lib/bootstrap/dist/js/datatables/DT_bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>