MediconEFC/Models/Dependente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MediconEFC.Models
{
    public class Dependente
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public string Cpf { get; set; }
        public Dependente()
        {

        }

        public Dependente(int id, string nome, string cpf)
        {
            Id = id;
            Nome = nome;
            Cpf = cpf;
        }
    }
}

MediconEFC/Controllers/DependenteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MediconEFC.Data;
using MediconEFC.Models;
using MediconEFC.Services;
using Medicon.UtilLocal;
using Newtonsoft.Json;


namespace MediconEFC.Controllers
{
    public class DependenteController : Controller
    {
        private readonly MediconEFCContext _context;
        private readonly DependenteService _dependenteService;
        private readonly MensagemService _mensagemService;

        public DependenteController(MediconEFCContext context, DependenteService dependenteService , MensagemService mensagemService)
        {
            _context = context;
            _dependenteService = dependenteService;
            _mensagemService = mensagemService;
        }

        #region chamadas assincronas

        // GET: Plano
        public async Task<IActionResult> Index()
        {
            var model = await _dependenteService.FindAllAsync();
            return View(model);
        }

        // GET: Plano/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: Plano/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Dependente não encontrado!" });
            }

            var obj = await _dependenteService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Dependente não encontrado!" });
            }

            return View(obj);
        }

        // GET: Plano/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Dependente não encontrado!" });
            }

            var obj = await _dependenteService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Dependente não encontrado!" });
            }

            return View(obj);
        }

        #endregion

        #region chamadas ajax

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CadastrarDependente(Dependente dependente, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();
            if (ModelState.IsValid)
            {
                if (!_dependenteService.ExistsDependente(dependente))
                {
                    try
                    {
                        _dependenteService.CadastrarDependente(dependente);

                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_155).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_155).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemSucesso;
                    }
                    catch (Exception)
                    {
                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemErro;

                    }
                }
                else
                {
                    data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_152).Numero;
                    data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_152).Decricao;
                    data.RedirecionarHome = true;
                    data.TituloMensagem = Constantes.TituloMensagemAlerta;
                }

                return Json(data, serializerSettings);
            }
            else
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

                return Json(data, serializerSettings);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AlterarDependente(int id, Dependente dependente, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            if (id != dependente.Id || !ModelState.IsValid)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_152).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_152).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            try
            {
                _dependenteService.AlterarDependente(dependente);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_160).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_160).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (ApplicationException)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_156).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

            }

            return Json(data, serializerSettings);
        }

        public JsonResult ExcluirDependente(int id, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            try
            {
                _dependenteService.RemoveDependente(id);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_153).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_153).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (Exception)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_159).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_159).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            return Json(data, serializerSettings);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }

        #endregion
    }
}

MediconEFC/Views/Dependente/Create.cshtml
@model MediconEFC.Models.Dependente

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Cadastrar novo dependente</h3>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="block">

            <div class="form-group">
                <form asp-action="Create" id="myformCreate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cpf " class="control-label"></label>
                        <input asp-for="Cpf" class="form-control" />
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-offset-9">
                        <input type="submit" value="Create" class="btn btn-success cssDeleteConfirm" />
                        <a asp-action="Index" class="btn btn-info">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script type="text/javascript">
        $(document).ready(function () {

            $('#myformCreate').on('submit', function (e) {
                e.preventDefault();
                //Enviar o formulário inteiro para controller "model"
                var formData = $(this).serialize();
                if (!formData.match(/=&|=$/)) {

                    $.post('/Dependente/CadastrarDependente', formData, function (data) {
                        $("#tipoMensagemResult").text(data.TituloMensagem);
                        $("#MsgResult").html(data.DescricaoMensagem);
                        $('#ModalResult').modal("show");

                    });
                }
            });

            $("#btnFecharModalResult").click(function () {
                window.location.href = '@Url.Action("Index", "Dependente")';
            });
        });
    </script>

}

MediconEFC/Views/Dependente/Details.cshtml
@model MediconEFC.Models.Dependente

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Histórico plano</h3>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="block">
            <div class="form-group col-md-12">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nome)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Nome)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Cpf)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Cpf)
                    </dd>
                </dl>
            </div>
            <div class="form-group col-md-offset-10">
                <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Edit</a>
                <a asp-action="Index" class="btn btn-info">Voltar</a>
            </div>
        </div>
    </div>
</div>

MediconEFC/Views/Dependente/Edit.cshtml
@model MediconEFC.Models.Dependente

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Alterar dependente</h3>
        </div>
    </div>
    <hr />

    <div class="row-fluid">
        <div class="block">

            <div class="form-group">
                <form asp-action="Edit" id="myformCreate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cpf" class="control-label"></label>
                        <input asp-for="Cpf" class="form-control" />
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-offset-9">
                        <input type="submit" value="Alterar" class="btn btn-success cssEdit" />
                        <a asp-action="Index" class="btn btn-info">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>

<!-- Modal Confirm -->
<div class="modal fade" data-backdrop="static" id="ModalConfirm" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemConfirm"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgConfirm"></p>
                <div class="modal-footer">
                    <input type="submit" value="Sim" class="btn btn-success cssEditConfirm" />
                    <input type="button" id="btnFecharModal" value="Não" class="btn btn-default" />
                </div>

            </div>

        </div>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {

            $('.cssEdit').on('click', function (e) {
                e.preventDefault();
                $("#tipoMensagemConfirm").text("Mensagem de confirmação");
                $("#MsgConfirm").html("Deseja realmente alterar dependente");
                $('#ModalConfirm').modal("show");

            });

            $('#btnFecharModal').on('click', function () {
                $("#ModalConfirm").modal("hide");
            });


            $('.cssEditConfirm').on('click', function (e) {
                e.preventDefault();

                    //Enviar o formulário inteiro para controller "model"
                    var formData = $('#myformCreate').serialize();
                    if (!formData.match(/=&|=$/)) {

                        $("#ModalConfirm").modal("hide");

                        $.post('/Dependente/AlterarDependente', formData, function (data) {
                            $("#tipoMensagemResult").text(data.TituloMensagem);
                            $("#MsgResult").html(data.DescricaoMensagem);
                            $('#ModalResult').modal("show");

                        });
                    }
            });

            $("#btnFecharModalResult").click(function () {
                window.location.href = '@Url.Action("Index", "Dependente")';
            });

        });

    </script>

}

MediconEFC/Views/Dependente/Index.cshtml
@model IEnumerable<MediconEFC.Models.Dependente>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-primary ">
    <div class="panel-heading panel panel-primary text-center small">
        <h3 class="panel-title">Dependente</h3>
    </div>
    <p class="pCreateNew">
        <a asp-action="Create" class="btn btn-default">Novo dependente</a>
    </p>
    <hr />
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="block-content collapse in">
                <div class="span12">
                    <table class="table table-hover table-striped table-bordered" id="tabelaOrdenada">
                        <thead>
                            <tr>
                                <th width="40%">
                                    @Html.DisplayNameFor(model => model.Nome)
                                </th>
                                <th width="20%">
                                    @Html.DisplayNameFor(model => model.Cpf)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cpf)
                                    </td>
                                    <td>

                                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary carregar hidden-print">Alterar</a>
                                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info carregar hidden-print">Histórico</a>
                                        <input type="button" id="btnDelete" value="Delete" asp-route-id="@item.Id" class="btn btn-danger cssDelete" />

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @*</form>*@
</div>




<div class="modal fade" data-backdrop="static" id="ModalDelete" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Mensagem de confirmação</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="idDelete" value="" />
                <p> Deseja realmente excluir este dependente?</p>
            </div>
            <div class="modal-footer">
                <a asp-action="Delete" id="btnDelete" class="btn btn-danger cssDeleteConfirm carregar hidden-print">Sim</a>
                <input type="button" id="btnFecharModal" value="Não" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>


@section Scripts{
    <script type="text/javascript">
        $('.cssDelete').on('click', function () {
            var id = $(this).attr("asp-route-id");
            $('.cssDeleteConfirm').attr('asp-route-id', id);
            $('#ModalDelete').modal("show");
        });

        $('#btnFecharModal').on('click', function () {
            $("#ModalDelete").modal("hide");
        });

        $("body").on("click", ".cssDeleteConfirm", function (e) {
            e.preventDefault();

            $("#ModalDelete").modal("hide");

            var _id = $(this).attr("asp-route-id");
            $.ajax({
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                type: 'GET',
                url: 'Dependente/ExcluirDependente',
                data: { id: _id },
                success: function (data) {
                    //$('#divCarregando').fadeOut('slow');
                    $("#tipoMensagemResult").text(data.TituloMensagem);
                    $("#MsgResult").html(data.DescricaoMensagem);
                    $('#ModalResult').modal("show");
                }
            });
        });

        $("#btnFecharModalResult").click(function () {
            window.location.href = '@Url.Action("Index", "Dependente")';
        });


    </script>
}