MediconEFC/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MediconEFC.Models
{
    public class Cliente
    {

        /// <summary>
        /// Carregar endereço a partir do cep
        /// http://www.eduardorizo.com.br/2014/12/04/correios-webservice-para-consulta-de-enderecos-a-partir-de-um-cep/
        /// </summary>

        /// <summary>
        /// Validação de email 
        /// http://www.eduardopires.net.br/2013/04/mvc-validando-dados-com-dataannotations/
        /// </summary>

        /// <summary>
        /// Validação de cpf valido
        /// https://github.com/lucas-silva/mvczin/tree/master/Mvczin.Web/Mvc/Validation
        /// </summary>

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public string Cpf { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        [Required(ErrorMessage = "Campo {0} não foi preenchido.")]
        [Display(Name = "E-mail")]
        [RegularExpression(@"^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*\s*$", ErrorMessage = "E-mail em formato inválido.")]
        public string Email { get; set; }
        public string Observacao { get; set; }
        public bool Ativo { get; set; }

        public Cliente()
        {

        }

        public Cliente(int id, string nome, string cpf, string cep, string endereco, int numero, string complemento, string bairro, string cidade, string estado, string telefone, string celular, string email, string observacao, bool ativo)
        {
            Id = id;
            Nome = nome;
            Cpf = cpf;
            Cep = cep;
            Endereco = endereco;
            Numero = numero;
            Complemento = complemento;
            Bairro = bairro;
            Cidade = cidade;
            Estado = estado;
            Telefone = telefone;
            Celular = celular;
            Email = email;
            Observacao = observacao;
            Ativo = ativo;
        }
    }

}

MediconEFC/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MediconEFC.Data;
using MediconEFC.Models;
using MediconEFC.Services;
using Newtonsoft.Json;
using Medicon.UtilLocal;
using System.Diagnostics;

namespace MediconEFC.Controllers
{
    public class ClienteController : Controller
    {
        private readonly MediconEFCContext _context;
        private readonly ClienteService _clienteService;
        private readonly MensagemService _mensagemService;

        public ClienteController(MediconEFCContext context, ClienteService clienteService, MensagemService mensagemService)
        {
            _context = context;
            _clienteService = clienteService;
            _mensagemService = mensagemService;
        }

        // GET: Cliente
        public async Task<IActionResult> Index()
        {
            var model = await _clienteService.FindAllAsync();
            return View(model);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Cliente não encontrado!" });
            }

            var obj = await _clienteService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Cliente não encontrado!" });
            }

            return View(obj);
        }

        // GET: Cliente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Cliente não encontrado!" });
            }

            var obj = await _clienteService.FindByIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Cliente não encontrado!" });
            }

            return View(obj);
        }

        #region chamadas ajax

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CadastrarCliente(Cliente cliente, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();
            if (ModelState.IsValid)
            {
                if (!_clienteService.ExistsCliente(cliente))
                {
                    try
                    {
                        cliente.Ativo = true;//TODO: Sempre que for cadastro já setar como ativo e tirar a opção da tela para que o usuário não cadastre uma equipe inativa.
                        _clienteService.CadastrarCliente(cliente);

                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_137).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_137).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemSucesso;
                    }
                    catch (Exception)
                    {
                        data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_138).Numero;
                        data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_138).Decricao;
                        data.RedirecionarHome = true;
                        data.TituloMensagem = Constantes.TituloMensagemErro;

                    }
                }
                else
                {
                    data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_139).Numero;
                    data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_139).Decricao;
                    data.RedirecionarHome = true;
                    data.TituloMensagem = Constantes.TituloMensagemAlerta;
                }

                return Json(data, serializerSettings);
            }
            else
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_138).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_138).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

                return Json(data, serializerSettings);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AlterarCliente(Cliente cliente, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            if (cliente.Id <= 0 || !ModelState.IsValid)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_135).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_135).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            try
            {
                _clienteService.AlterarCliente(cliente);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_131).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_131).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (ApplicationException)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_141).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_141).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;

            }

            return Json(data, serializerSettings);
        }

        public JsonResult ExcluirCliente(int id, JsonSerializerSettings serializerSettings)
        {
            MensagemRetornoViewModel data = new MensagemRetornoViewModel();

            try
            {
                _clienteService.RemoveCliente(id);

                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_134).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_134).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemSucesso;
            }
            catch (Exception)
            {
                data.NumeroMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_133).Numero;
                data.DescricaoMensagem = _mensagemService.RetornarMensagemPorNumero(Constantes.MENSAGEM_133).Decricao;
                data.RedirecionarHome = true;
                data.TituloMensagem = Constantes.TituloMensagemErro;
            }

            return Json(data, serializerSettings);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }

        #endregion
    }
}

MediconEFC/Views/Cliente/Create.cshtml
@model MediconEFC.Models.Cliente

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Cadastrar novo cliente</h3>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="block">

            <div class="form-group">
                <form asp-action="Create" id="myformCreate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cpf" class="control-label"></label>
                        <input asp-for="Cpf" class="form-control" />
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cep" class="control-label"></label>
                        <input asp-for="Cep" class="form-control" />
                        <span asp-validation-for="Cep" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Endereco" class="control-label"></label>
                        <input asp-for="Endereco" class="form-control" />
                        <span asp-validation-for="Endereco" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Numero" class="control-label"></label>
                        <input asp-for="Numero" class="form-control" />
                        <span asp-validation-for="Numero" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Complemento" class="control-label"></label>
                        <input asp-for="Complemento" class="form-control" />
                        <span asp-validation-for="Complemento" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Bairro" class="control-label"></label>
                        <input asp-for="Bairro" class="form-control" />
                        <span asp-validation-for="Bairro" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cidade" class="control-label"></label>
                        <input asp-for="Cidade" class="form-control" />
                        <span asp-validation-for="Cidade" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Estado" class="control-label"></label>
                        <input asp-for="Estado" class="form-control" />
                        <span asp-validation-for="Estado" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Telefone" class="control-label"></label>
                        <input asp-for="Telefone" class="form-control" />
                        <span asp-validation-for="Telefone" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Observacao" class="control-label"></label>
                        <input asp-for="Observacao" class="form-control" />
                        <span asp-validation-for="Observacao" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-offset-9">
                        <input type="submit" value="Create" class="btn btn-success cssDeleteConfirm" />
                        <a asp-action="Index" class="btn btn-info">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {
            $("#Telefone").inputmask("mask", { "mask": "(99)9999-9999" });
            $("#Celular").inputmask("mask", { "mask": "(99)99999-9999" });
            $("#Cep").inputmask("mask", { "mask": "99.999-999" });
            $("#Cpf").inputmask("mask", { "mask": "999.999.999-99" });

            $('#myformCreate').on('submit', function (e) {
                e.preventDefault();
                //Enviar o formulário inteiro para controller "model"
                var formData = $(this).serialize();
                if (!formData.match(/=&|=$/)) {

                    $.post('/Cliente/CadastrarCliente', formData, function (data) {
                        $("#tipoMensagemResult").text(data.TituloMensagem);
                        $("#MsgResult").html(data.DescricaoMensagem);
                        $('#ModalResult').modal("show");

                    });
                }
            });

            $("#btnFecharModalResult").click(function () {
                window.location.href = '@Url.Action("Index", "Cliente")';
            });

            ///Validação de cpf
            $("#Cpf").change(function () {
                var cpf = $("#Cpf").val();
                if (!validaCPF(cpf)) {
                    //Limpar se CPF for invalido
                    $("#Cpf").val('');
                }                
            });

        });

        ///Validação de CPF
        function validaCPF(cpf) {
            var numeros, digitos, soma, i, resultado, pos, tamanho, digitos_iguais;
            digitos_iguais = 1;
            var retorno = false;

            for (i = 0; i < cpf.length - 1; i++) {
                if (cpf.charAt(i) != cpf.charAt(i + 1)) {
                    digitos_iguais = 0;
                    break;
                }
            }

            if (!digitos_iguais) {
                cpf = cpf.replace(/[^\d]+/g, '');
                if (cpf == '') return false;
                // Elimina CPFs invalidos conhecidos    
                if (cpf.length != 11 ||
                    cpf == "00000000000" ||
                    cpf == "11111111111" ||
                    cpf == "22222222222" ||
                    cpf == "33333333333" ||
                    cpf == "44444444444" ||
                    cpf == "55555555555" ||
                    cpf == "66666666666" ||
                    cpf == "77777777777" ||
                    cpf == "88888888888" ||
                    cpf == "99999999999")
                    return false;
                // Valida 1o digito 
                add = 0;
                for (i = 0; i < 9; i++)
                    add += parseInt(cpf.charAt(i)) * (10 - i);
                rev = 11 - (add % 11);
                if (rev == 10 || rev == 11)
                    rev = 0;
                if (rev != parseInt(cpf.charAt(9)))
                    return false;
                // Valida 2o digito 
                add = 0;
                for (i = 0; i < 10; i++)
                    add += parseInt(cpf.charAt(i)) * (11 - i);
                rev = 11 - (add % 11);
                if (rev == 10 || rev == 11)
                    rev = 0;
                if (rev != parseInt(cpf.charAt(10)))
                    return false;
                return true;
            }
            else {
                return false;
            }
            return this.optional(element) || retorno;
        }

    </script>

}

MediconEFC/Views/Cliente/Edit.cshtml
@model MediconEFC.Models.Cliente

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-primary">
    <div class="panel panel-primary text-center">
        <div class="panel-heading">
            <h3 class="panel-title">Alterar cliente</h3>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="block">
            <div class="form-group">
                <form asp-action="Edit" id="myformCreate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cpf" class="control-label"></label>
                        <input asp-for="Cpf" class="form-control" />
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cep" class="control-label"></label>
                        <input asp-for="Cep" class="form-control" />
                        <span asp-validation-for="Cep" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Endereco" class="control-label"></label>
                        <input asp-for="Endereco" class="form-control" />
                        <span asp-validation-for="Endereco" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Numero" class="control-label"></label>
                        <input asp-for="Numero" class="form-control" />
                        <span asp-validation-for="Numero" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Complemento" class="control-label"></label>
                        <input asp-for="Complemento" class="form-control" />
                        <span asp-validation-for="Complemento" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Bairro" class="control-label"></label>
                        <input asp-for="Bairro" class="form-control" />
                        <span asp-validation-for="Bairro" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Cidade" class="control-label"></label>
                        <input asp-for="Cidade" class="form-control" />
                        <span asp-validation-for="Cidade" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Estado" class="control-label"></label>
                        <input asp-for="Estado" class="form-control" />
                        <span asp-validation-for="Estado" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Telefone" class="control-label"></label>
                        <input asp-for="Telefone" class="form-control" />
                        <span asp-validation-for="Telefone" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" />
                        <span asp-validation-for="Celular" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group col-md-11 col-md-offset-1">
                        <label asp-for="Observacao" class="control-label"></label>
                        <input asp-for="Observacao" class="form-control" />
                        <span asp-validation-for="Observacao" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-11 col-md-offset-1">
                        <div class="checkbox">
                            <label>
                                <input asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                            </label>
                        </div>
                    </div>
                    <div class="form-group col-md-offset-9">
                        <input type="submit" value="Alterar" class="btn btn-success cssEdit" />
                        <a asp-action="Index" class="btn btn-info">Voltar</a>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>


<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="ModalResult" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemResult"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgResult"></p>
            </div>
            <div class="modal-footer">
                <input type="button" id="btnFecharModalResult" value="Fechar" class="btn btn-default" />

            </div>
        </div>

    </div>
</div>

<!-- Modal Confirm -->
<div class="modal fade" data-backdrop="static" id="ModalConfirm" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="tipoMensagemConfirm"></h4>
            </div>
            <div class="modal-body">
                <p id="MsgConfirm"></p>
                <div class="modal-footer">
                    <input type="submit" value="Sim" class="btn btn-success cssEditConfirm" />
                    <input type="button" id="btnFecharModal" value="Não" class="btn btn-default" />
                </div>

            </div>

        </div>

    </div>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {            
            $("#Telefone").inputmask("mask", { "mask": "(99)9999-9999" });
            $("#Celular").inputmask("mask", { "mask": "(99)99999-9999" });
            $("#Cep").inputmask("mask", { "mask": "99.999-999" });
            $("#Cpf").inputmask("mask", { "mask": "999.999.999-99" });

            $('.cssEdit').on('click', function (e) {
                e.preventDefault();
                $("#tipoMensagemConfirm").text("Mensagem de confirmação");
                $("#MsgConfirm").html("Deseja realmente alterar cliente?");
                $('#ModalConfirm').modal("show");

            });

            $('#btnFecharModal').on('click', function () {
                $("#ModalConfirm").modal("hide");
            });

            $('.cssEditConfirm').on('click', function (e) {
                e.preventDefault();
                //Enviar o formulário inteiro para controller "model"
                var formData = $('#myformCreate').serialize();
                if (!formData.match(/=&|=$/)) {

                    $("#ModalConfirm").modal("hide");

                    $.post('/Cliente/AlterarCliente', formData, function (data) {
                        $("#tipoMensagemResult").text(data.TituloMensagem);
                        $("#MsgResult").html(data.DescricaoMensagem);
                        $('#ModalResult').modal("show");

                    });
                }
            });


            $("#btnFecharModalResult").click(function () {
                window.location.href = '@Url.Action("Index", "Cliente")';
            });


        });
    </script>
}